# Site wide configuration

title:            Peikk0's blog
locale:           en_US
url:              http://segmentationfau.lt


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pierre Guinoiseau
  avatar: bio-photo.png
  bio: BOFH, Linux/FreeBSD sysadmin, DevOps, amateur photographer, guitar
       player, drummer, metal-head, NZ lover, bacon eater...
  email: pierre(at)guinoiseau(dot)eu
  disqus-shortname: segmentationfau-lt
  twitter: peikk00
  facebook: 
  google:
    plus: PierreGuinoiseau
    analytics: 
    verify: ibpeDNTri1G1ZCeTObRe0Xx2gzZpAd4VBnd1yebR6QA
    ad-client: 
    ad-slot: 
  bing-verify: 
  piwik:
      id: 4
      host: stats.sig11.fr
  github: peikk0
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: pierreguinoiseau
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: peikk0
  dribbble: #username
  youtube: peikk00
  soundcloud: #username
  weibo: #username
  flickr: geekounet
  500px: peikk0

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
