# Site wide configuration

title:            Peikk0's blog
locale:           en_NZ
url:              http://segmentationfau.lt


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Pierre Guinoiseau
  avatar: bio-photo.jpg
  bio: BOFH, Linux/Unix sysadmin, DevOps engineer, amateur photographer,
       guitar player, drummer, metal-head, NZ lover, bacon eater...
  email: pierre(at)guinoiseau(dot)eu
  disqus-shortname: segmentationfau-lt
  twitter: peikk00
  facebook:
  google:
    plus: PierreGuinoiseau
    analytics:
    verify: ibpeDNTri1G1ZCeTObRe0Xx2gzZpAd4VBnd1yebR6QA
    ad-client:
    ad-slot:
  bing-verify:
  piwik:
      id: 4
      host: stats.sig11.fr
  github: peikk0
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: pierreguinoiseau
  instagram: peikk00
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: peikk0
  dribbble: #username
  youtube: peikk00
  soundcloud: #username
  weibo: #username
  flickr: geekounet
  500px: peikk0
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
